name: sagali_light
description: "Bitcoin Ligtning Wallet."
publish_to: 'none'
version: 0.1.1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.1.5
  font_awesome_flutter: ^10.7.0
  qr_code_scanner_plus: ^2.0.10
  permission_handler: ^11.3.0
  qr_flutter: ^4.1.0
  share_plus: ^7.2.1
  shared_preferences: ^2.2.2
  rxdart: ^0.28.0
  bip39: ^1.0.6
  bdk_flutter: ^0.30.0
  flutter_secure_storage: ^9.0.0
  local_auth: ^2.3.0
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/